index:
   path: /
   controller: App\Controller\BaseController::index

add_person:
   path: /add_person
   controller: App\Controller\BaseController::addPerson

view_all_persons:
   path: /view_all_persons
   controller: App\Controller\BaseController::viewAll

api_requests:
   path: /api_requests
   controller: App\Controller\BaseController::apiPage